// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHzlnHehpKmGZ_Vn3nmJ5_Ss48ROJ_5w',
    appId: '1:619269315577:web:b36bc5dc0bb0410576fb28',
    messagingSenderId: '619269315577',
    projectId: 'mypitch-d4f22',
    authDomain: 'mypitch-d4f22.firebaseapp.com',
    storageBucket: 'mypitch-d4f22.appspot.com',
    measurementId: 'G-KRETJ751S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5Vj7BDq1cnmB7YR8CxSzMt7FMy_Hjeg',
    appId: '1:619269315577:android:85abd6c1966642b076fb28',
    messagingSenderId: '619269315577',
    projectId: 'mypitch-d4f22',
    storageBucket: 'mypitch-d4f22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGl_skaC-byfJh2S6rsMgoF9V5R1DHg-w',
    appId: '1:619269315577:ios:836a4b6ddb41873976fb28',
    messagingSenderId: '619269315577',
    projectId: 'mypitch-d4f22',
    storageBucket: 'mypitch-d4f22.appspot.com',
    iosBundleId: 'com.example.myPitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGl_skaC-byfJh2S6rsMgoF9V5R1DHg-w',
    appId: '1:619269315577:ios:836a4b6ddb41873976fb28',
    messagingSenderId: '619269315577',
    projectId: 'mypitch-d4f22',
    storageBucket: 'mypitch-d4f22.appspot.com',
    iosBundleId: 'com.example.myPitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChHzlnHehpKmGZ_Vn3nmJ5_Ss48ROJ_5w',
    appId: '1:619269315577:web:b3b0993119c8c9db76fb28',
    messagingSenderId: '619269315577',
    projectId: 'mypitch-d4f22',
    authDomain: 'mypitch-d4f22.firebaseapp.com',
    storageBucket: 'mypitch-d4f22.appspot.com',
    measurementId: 'G-S36GNLGBVE',
  );
}
